import type { ThemeSpec } from "../theme-types";
import {
  createThemeButton,
  createThemeEffects,
  createThemeMotion,
  createThemeTypography,
} from "./rich-config";

export const neuBrutalismTheme: ThemeSpec = {
  id: "neu-brutalism",
  name: "Neu-Brutalism",
  description: "Sticker-stack surfaces, hard shadows, and anti-polish color blocking.",
  colorScheme: "light",
  palette: {
    primary: "#FF6B6B",
    secondary: "#E5B800",
    accent: "#9B8AE0",
    success: "#16A34A",
    warning: "#E5B800",
    danger: "#DC2626",
    text: "#000000",
    textMuted: "#555555",
  },
  typography: createThemeTypography({
    heading: "Space Grotesk, Bebas Neue, Impact, sans-serif",
    body: "Rubik, DM Sans, sans-serif",
    mono: "Space Mono, monospace",
    weights: { bold: 400, normal: 600 },
    en: {
      body: "'Rubik', 'DM Sans', sans-serif",
      heading: "'Space Grotesk', 'Bebas Neue', sans-serif",
      mono: "'Space Mono', monospace",
    },
  }),
  effects: createThemeEffects({
    glowColor: "#FF6B6B",
    shadowColor: "#000000",
    shimmerColor: "#FFF2AE",
    pattern: "halftone",
    gradientAngle: 0,
    noiseOpacity: 0,
    borderStyle: "solid",
    borderWidth: "4px",
    borderRadius: "0px",
    hover: {
      glowIntensity: 0,
      glowSpread: 0,
      shadowIntensity: 0.9,
      shadowOffset: "8px 8px 0 #000000",
      shimmer: false,
      scanlines: false,
      chromatic: false,
      hologram: false,
      lightTrails: false,
      colorShift: false,
      dataStream: false,
    },
    background: {
      gradient: false,
      noise: false,
      pattern: "halftone",
      gridSize: 14,
      gridOpacity: 0.12,
    },
    border: {
      glow: false,
      animated: false,
      cornerClip: true,
      clipSize: 0,
    },
  }),
  button: createThemeButton({
    type: "flat-shadow",
    raiseLevel: 7,
    springRelease: false,
    activeOpacity: 1,
    backgroundActive: "#FF6B6B",
    backgroundDarker: "#F14D4D",
    backgroundShadow: "#000000",
    shadowOffset: "6px 6px 0 #000000",
    progressEnabled: true,
    progressColor: "#E5B800",
    snapShadow: true,
  }),
  foundation: {
    background: "#FFFDF5",
    backgroundPattern: "brutalist-halftone",
    surface: "#FFFFFF",
    surfaceAccent: "#C4B5FD",
    sidebarBackground: "#FFD93D",
    borderColor: "#000000",
    borderWidth: 4,
    borderStyle: "solid",
    radius: 0,
    shadow: "8px 8px 0px 0px #000000",
    shadowSm: "4px 4px 0px 0px #000000",
    shadowLg: "12px 12px 0px 0px #000000",
    shadowHover: "12px 12px 0px 0px #000000",
    shadowPressed: "2px 2px 0px 0px #000000",
    shadowDanger: "8px 8px 0px 0px #000000",
  },
  depth: {
    buttonShadow: "4px 4px 0 #000000",
    buttonShadowHover: "7px 7px 0 #000000",
    buttonShadowPressed: "2px 2px 0 #000000",
    cardShadow: "6px 6px 0 #000000",
    cardShadowHover: "9px 9px 0 #000000",
    inputInsetShadow: "4px 4px 0 #cccccc",
    switchShadow: "2px 2px 0 #000000",
    dropdownShadow: "4px 4px 0 #000000",
  },
  componentProfile: {
    button: "sticker-switch",
    input: "hard-outline",
    table: "ink-grid",
    panel: "sticker-stack",
  },
  dataUi: {
    density: "chunky",
    rowSeparator: "thick",
    statusShape: "square",
  },
  overlays: {
    toastTone: "sticker-banner",
    modalBackdrop: "rgba(0, 0, 0, 0.55)",
    commandPaletteFrame: "poster-stack",
  },
  motion: createThemeMotion({
    enterMs: 220,
    exitMs: 130,
    easing: "cubic-bezier(0.2, 0, 0, 1)",
    bounce: 0,
    hoverScale: 1,
    hoverDuration: 100,
    tiltEnabled: false,
    tiltDegree: 0,
    springRelease: false,
    pressMs: 80,
    distancePx: 2,
  }),
  signatures: ["hard-shadow", "sticker-slam", "halftone", "anti-corporate"],
};


