import type { ThemeSpec } from "../theme-types";
import {
  createThemeButton,
  createThemeEffects,
  createThemeMotion,
  createThemeTypography,
} from "./rich-config";

export const defaultTheme: ThemeSpec = {
  id: "default",
  name: "Default",
  description: "Production-neutral baseline theme.",
  palette: {
    primary: "#3B82F6",
    secondary: "#6366F1",
    accent: "#14B8A6",
    success: "#22C55E",
    warning: "#EAB308",
    danger: "#EF4444",
    text: "#0F172A",
    textMuted: "#5F6F86",
  },
  typography: createThemeTypography({
    display: "Inter, -apple-system, BlinkMacSystemFont, sans-serif",
    body: "Inter, -apple-system, BlinkMacSystemFont, sans-serif",
    mono: "JetBrains Mono, Menlo, Monaco, monospace",
    displayWeight: 600,
    bodyWeight: 400,
  }),
  effects: createThemeEffects({
    glowColor: "#3B82F6",
    shadowColor: "#1D4ED8",
    shimmerColor: "#14B8A6",
    pattern: null,
    gradientAngle: 128,
    noiseOpacity: 0.03,
    borderRadius: "12px",
    hover: {
      glowIntensity: 0.4,
      glowSpread: 14,
      shadowIntensity: 0.32,
      shimmerDuration: 1050,
    },
    border: {
      animated: false,
    },
  }),
  button: createThemeButton({
    type: "standard",
    raiseLevel: 3,
    springRelease: true,
    activeOpacity: 0.9,
    backgroundActive: "#2563EB",
    backgroundDarker: "#1D4ED8",
    backgroundShadow: "#1E40AF",
    shadowOffset: "0 3px 10px rgba(30,64,175,0.25)",
    progressEnabled: true,
    progressColor: "#14B8A6",
  }),
  foundation: {
    background: "#F6F7FB",
    backgroundPattern: "none",
    surface: "#FFFFFF",
    surfaceAccent: "#F3F4F6",
    sidebarBackground: "#F9FAFB",
    borderColor: "#9AA8BD",
    borderWidth: 1,
    borderStyle: "solid",
    radius: 12,
    shadow: "0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)",
    shadowSm: "0 1px 2px rgba(0,0,0,0.05)",
    shadowLg: "0 10px 24px rgba(17,24,39,0.08)",
    shadowHover: "0 4px 12px rgba(0,0,0,0.1)",
    shadowPressed: "0 1px 1px rgba(0,0,0,0.08)",
    shadowDanger: "0 0 0 1px rgba(220,38,38,0.25), 0 2px 6px rgba(220,38,38,0.15)",
  },
  depth: {
    buttonShadow: "0 1px 3px rgba(0,0,0,0.1)",
    buttonShadowHover: "0 4px 12px rgba(0,0,0,0.1)",
    buttonShadowPressed: "0 1px 1px rgba(0,0,0,0.08)",
    cardShadow: "0 1px 3px rgba(0,0,0,0.1)",
    cardShadowHover: "0 4px 12px rgba(0,0,0,0.1)",
    inputInsetShadow: "none",
    switchShadow: "none",
    dropdownShadow: "0 4px 12px rgba(0,0,0,0.08)",
  },
  componentProfile: {
    button: "soft-elevation",
    input: "quiet-outline",
    table: "subtle-grid",
    panel: "layered-card",
  },
  dataUi: {
    density: "comfortable",
    rowSeparator: "subtle",
    statusShape: "pill",
  },
  overlays: {
    toastTone: "neutral",
    modalBackdrop: "rgba(15, 23, 42, 0.35)",
    commandPaletteFrame: "soft-border",
  },
  motion: createThemeMotion({
    enterMs: 220,
    exitMs: 180,
    easing: "cubic-bezier(0.2, 0.8, 0.2, 1)",
    bounce: 0.15,
    hoverScale: 1.02,
    hoverDuration: 140,
    tiltEnabled: true,
    tiltDegree: 6,
    springRelease: true,
    pressMs: 100,
    distancePx: 6,
  }),
  signatures: ["neutral", "clean", "balanced"],
};
