import type { ThemeSpec } from "../theme-types";

export const neuBrutalismTheme: ThemeSpec = {
  id: "neu-brutalism",
  name: "Neu-Brutalism",
  description: "Sticker-stack surfaces, hard shadows, and anti-polish color blocking.",
  palette: {
    primary: "#FF6B6B",
    secondary: "#FFD93D",
    accent: "#C4B5FD",
    success: "#22C55E",
    warning: "#FFD93D",
    danger: "#FF3B30",
    text: "#000000",
    textMuted: "#000000",
  },
  typography: {
    display: "Space Grotesk, sans-serif",
    body: "Space Grotesk, sans-serif",
    mono: "Space Mono, monospace",
  },
  foundation: {
    background: "#FFFDF5",
    backgroundPattern: "brutalist-halftone",
    surface: "#FFFFFF",
    surfaceAccent: "#C4B5FD",
    sidebarBackground: "#FFD93D",
    borderColor: "#000000",
    borderWidth: 4,
    borderStyle: "solid",
    radius: 0,
    shadow: "8px 8px 0px 0px #000000",
    shadowSm: "4px 4px 0px 0px #000000",
    shadowLg: "12px 12px 0px 0px #000000",
    shadowHover: "12px 12px 0px 0px #000000",
    shadowPressed: "2px 2px 0px 0px #000000",
    shadowDanger: "8px 8px 0px 0px #000000",
    shadowFocus: "0 0 0 4px #000000",
    focusRing: "0 0 0 4px #000000",
  },
  componentProfile: {
    button: "sticker-switch",
    input: "hard-outline",
    table: "ink-grid",
    panel: "sticker-stack",
  },
  dataUi: {
    density: "chunky",
    rowSeparator: "thick",
    statusShape: "square",
  },
  overlays: {
    toastTone: "sticker-banner",
    modalBackdrop: "rgba(0, 0, 0, 0.55)",
    commandPaletteFrame: "poster-stack",
  },
  motion: {
    enterMs: 180,
    exitMs: 130,
    hoverMs: 100,
    pressMs: 80,
    easing: "linear",
    overshoot: 0,
    distancePx: 2,
  },
  signatures: ["hard-shadow", "sticker-stack", "halftone", "anti-corporate"],
};
